[[redirects]]
  from="/:country/:lng/db/*"
  to="https://db.netlify-se-test.com/:splat"
  status=200

  [[context.production.redirects]]
  from = '/_next/data/*'
  to = 'https://db.netlify-se-test.com/_next/data/:splat'
  status = 301
  force=true