
[[redirects]]
  from="/:country/:lng/db/*"
  to="https://db.netlify-se-test.com/:splat"
  status=200


[[redirects]]
  from="/_next/data/db/*"
  to="https://db.netlify-se-test.com/_next/data/db/:splat"
  status=200

